name: feature_make
description: 구현해야 할 기능에 대한 설명을 위한 템플릿
title: "[FeatureMake] 이슈제목"
labels: ["분류: 기능 구현", "상태: 도움 필요"]
body:
  - type: markdown
    attributes:
      value: |
        **※ Architecture repo 및 Project board에 기록되어 있는 기능 구현을 위한 안내입니다.**
        **※ 본인이 직접 기능 구현을 원하신다면 자기 자신을, 다른 멤버에게 요청하고 싶다면 해당 멤버를 Assignees에 꼭 지정해주세요.**

        **※ 기능 구현 완료 후 Pull Request 작성 시 해당 이슈를 꼭 연결해주세요!**
        **※ 이슈 내용에 변경이 필요한 경우(기능 세부 사항 등), 아래 Comment를 남겨주시고 Label에는 '상태: 재검토 필요'를 지정해주세요!**
        **※ 이슈 내용에 추가 정보가 필요한 경우(기능 세부 사항 등), 아래 Comment를 남겨주시고 Label에는 '상태: 추가 정보 필요'를 지정해주세요!**


  - type: input
    id: writer
    attributes:
      label: 작성자
      description: 작성하신 분 이름을 적어주세요(신속한 작성자 구분 목적)
      placeholder: ex. 안경호
    validations:
      required: true

  - type: textarea
    id: explaination
    attributes:
      label: 1. 기능에 대한 설명
      description: 구현해야 할 기능에 대한 설명을 남겨주세요. (기능의 목적, 기대 효과 등)
      placeholder: 기능의 목적, 기대 효과 등
    validations:
      required: true

  - type: textarea
    id: dataio
    attributes:
      label: 2. 인풋(매개변수) & 아웃풋(return 값) (optional)
      description: |
                  구현해야 할 기능이 함수인 경우 인풋과 아웃풋에 대한 설명을 남겨주세요.
                  ex. 인풋 : JSON으로 변환된 데이터프레임
                  아웃풋 : 함수 연산을 거친 후 JSON으로 변환된 데이터프레임
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 3. 추가 내용 (optional)
      description: |
                  위 사항 외에 추가로 남기실 내용이 있다면 작성해주세요.
                  (텍스트 외 스크린샷 등의 이미지 첨부 가능)
    validations:
      required: false