name: feature_request
description: 기능 추가 또는 요청을 위한 템플릿
title: "[FeatureReq] 이슈제목"
labels: ["분류: 기능 추가 요청", "상태: 도움 필요"]
assignees: 
  - seahahn
body:
  - type: markdown
    attributes:
      value: |
        **※ Architecture repo 및 Project board에 기록되어 있는 기능 목록 외의 기능을 추가 또는 요청하기 위한 템플릿입니다.**
        **※ 본인이 직접 기능 추가를 원하신다면 자기 자신을, 다른 멤버에게 요청하고 싶다면 해당 멤버를 Assignees에 꼭 지정해주세요.**
        **※ 안경호(seahahn)는 Assignees에 기본 지정되어 있습니다. 해제하지 말아주세요!**
  - type: markdown
    attributes:
      value: |
        **※ 우측 Projects 지정 필요 : **
        - **Repository : 해당 Repo의 Project Board**
        - **Organization : Phase 1(MLML) Progress Board, WebApp Board**
  - type: input
    id: writer
    attributes:
      label: 작성자
      description: 작성하신 분 이름을 적어주세요(신속한 작성자 구분 목적)
      placeholder: ex. 안경호
    validations:
      required: true

  - type: textarea
    id: explaination
    attributes:
      label: 1. 기능에 대한 설명
      description: 제안하시는 기능에 대한 설명을 남겨주세요. (버그와의 연관성, 기능의 목적, 기대 효과 등)
      placeholder: 버그와의 연관성, 기능의 목적, 기대 효과 등
    validations:
      required: true

  - type: textarea
    id: options
    attributes:
      label: 2. 대안 (optional)
      description: 제안하신 기능과 동일하거나 비슷한 결과를 가져올 수 있을 것 같은 다른 대안에 대한 생각이 있으시다면 남겨주세요.
                  상상의 나래 등의 Brain-ficial 가능
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: 3. 추가 내용 (optional)
      description: 위 사항 외에 추가로 남기실 내용이 있다면 작성해주세요.
                  (텍스트 외 스크린샷 등의 이미지 첨부 가능)
    validations:
      required: false